# coding=utf-8
import datetime

class Player(document):
    full_name = StringField(max_lenght=50)
    first_name = StringField(max_lenght=25)
    last_name = StringField(max_lenght=25)
    pdga_number = IntField(required=True)
    location_full = StringField(max_lenght=100)
    location_city = StringField(max_lenght=50)
    location_state = StringField(max_lenght=50)
    location_country = StringField(max_lenght=50)
    classification = StringField(max_lenght=25)
    member_since = IntField(max_lenght=4)
    membership_status = StringField(max_lenght=25)
    current_rating = IntField(max_lenght=5)
    highest_rating = IntField(max_lenght=5)
    lowest_rating = IntField(max_lenght=5)
    rating_difference = IntField(max_lenght=5)
    latest_rating_update = DateTimeField()
    total_events = IntField(max_lenght=6)
    total_wins = IntField(max_lenght=6)
    certified_status = BooleanField(default=False)
    certified_status_expiration_date = DateTimeField()
    career_earnings = FloatField()
    individual_tournament_years = ListField(IntField(max_lenght=5))
    pdga_page_link = URLField()
    played_event_ids = ListField(IntField(max_lenght=10))
    played_countries = ListField(StringField(max_lenght=50))
    first_crawl_date = DateTimeField(default=datetime.datetime.now)
    latest_update = DateTimeField(default=datetime.datetime.now)
    fields_updated = ListField(DynamicField())

class Tournaments(document):
    tournament_id = IntField()
    total_players = IntField()
    tournament_start = DateTimeField()
    tournament_end = DateTimeField()
    location_full = StringField(max_lenght=100)
    location_city = StringField(max_lenght=50)
    location_state = StringField(max_lenght=50)
    location_country = StringField(max_lenght=50)
    tournament_director = StringField()
    tournament_director_id = StringField()
    tournament_director_phone = StringField()
    tournament_director_email = StringField()
    assistant_director = StringField()
    assistant_director_id = StringField()
    website = URLField()
    tournament_tier = StringField()
    tournament_classification = StringField()
    pro_prize_money = FloatField()
    avg_total_player_par = IntField()
    avg_player_rating = IntField()
    avg_total_round_rating = IntField()
    avg_money_per_player = FloatField()
    rounds = ListField(EmbeddedDocumentField(TournamentRound))
    players = ListField(EmbeddedDocumentField(TournamentPlayer))
    first_crawl_date = DateTimeField(default=datetime.datetime.now)
    latest_update = DateTimeField(default=datetime.datetime.now)
    fields_updated = ListField(DynamicField())
    pdga_latest_update = DateTimeField()

class TournamentRound(EmbeddedDocument):
    division = StringField()
    round_number = IntField()
    avg_par = IntField()
    avg_throws = IntField()
    total_throws = IntField()
    avg_round_rating = IntField()
    round_holes = IntField()
    course_name = StringField()
    course_par = IntField()
    course_length_ft = IntField()
    course_length_meters = IntField()
    number_of_players = IntField()
    number_of_dns = IntField()
    number_of_dnf = IntField()

class TournamentPlayer(EmbeddedDocument):
    name = StringField()
    pdga_id = IntField()
    points = FloatField()
    total_throws = IntField()
    money_won = FloatField()
    placement = IntField()
    total_par = FloatField()
    avg_par = FloatField()
    avg_round_rating = FloatField()
    propagator = BooleanField()
    avg_placement = FloatField()
    division = StringField()
    dns = BooleanField(default=False)
    dnf = BooleanField(default=False)
    finished = BooleanField(default=True)
    rounds = ListField(EmbeddedDocumentField(PlayerIndividualRound))

class PlayerIndividualRound(EmbeddedDocument):
    round_number = IntField()
    par = IntField()
    throws = IntField()
    placement = IntField()
    round_rating = IntField()
    round_holes = IntField()
    course_name = StringField()
    course_par = IntField()
    course_length_ft = IntField()
    course_length_meters = IntField()
    dns = BooleanField(default=False)
    dnf = BooleanField(default=False)
