# coding=utf-8

US_STATES = {
    'ak': 'alaska',
    'al': 'alabama',
    'ar': 'arkansas',
    'as': 'american samoa',
    'az': 'arizona',
    'ca': 'california',
    'co': 'colorado',
    'ct': 'connecticut',
    'dc': 'district of columbia',
    'de': 'delaware',
    'fl': 'florida',
    'ga': 'georgia',
    'gu': 'guam',
    'hi': 'hawaii',
    'ia': 'iowa',
    'id': 'idaho',
    'il': 'illinois',
    'in': 'indiana',
    'ks': 'kansas',
    'ky': 'kentucky',
    'la': 'louisiana',
    'ma': 'massachusetts',
    'md': 'maryland',
    'me': 'maine',
    'mi': 'michigan',
    'mn': 'minnesota',
    'mo': 'missouri',
    'mp': 'northern mariana islands',
    'ms': 'mississippi',
    'mt': 'montana',
    'na': 'national',
    'nc': 'north carolina',
    'nd': 'north dakota',
    'ne': 'nebraska',
    'nh': 'new hampshire',
    'nj': 'new jersey',
    'nm': 'new mexico',
    'nv': 'nevada',
    'ny': 'new york',
    'oh': 'ohio',
    'ok': 'oklahoma',
    'or': 'oregon',
    'pa': 'pennsylvania',
    'pr': 'puerto Rico',
    'ri': 'rhode Island',
    'sc': 'south Carolina',
    'sd': 'south Dakota',
    'tn': 'tennessee',
    'tx': 'texas',
    'ut': 'utah',
    'va': 'virginia',
    'vi': 'virgin Islands',
    'vt': 'vermont',
    'wa': 'washington',
    'wi': 'wisconsin',
    'wv': 'west Virginia',
    'wy': 'wyoming'
    }


US_STATES_LIST = ["Alabama","Alaska","Arizona","Arkansas","California","Colorado",
  "Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois",
  "Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland",
  "Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana",
  "Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York",
  "North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania",
  "Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah",
  "Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"]

MONTH_DICT = {
        "Jan":"01",
        "Feb":"02",
        "Mar":"03",
        "Apr":"04",
        "May":"05",
        "Jun":"06",
        "Jul":"07",
        "Aug":"08",
        "Sep":"09",
        "Oct":"10",
        "Nov":"11",
        "Dec":"12"
        }

ACCEPTED_STATUSES = ['ace club', 'eagle club', 'birdie club', 'active', 'current']


HISTORY_FIELDS = [
        "latest_update",
        "membership",
        "membership_status",
        "membership_status_expiration_date",
        "first_name", 
        "middle_name",
        "last_name",
        "city",
        "state",
        "country",
        "classification",
        "career_earnings",
        "total_wins",
        "lowest_rating",
        "highest_rating",
        "current_rating",
        "rating_difference",
        "individual_tournament_years",
        "certified_status",
        "certified_status_expiration_date",
    ]


HISTORY_FIELDS_TOURNAMENT = [
        "latest_update",
        "tournament_name",
        "city",
        "state",
        "country",
        "tournament_start",
        "tournament_end",
        "tournament_length_days",
        "tournament_director",
        "tournament_director_id",
        "assistant_director",
        "assistant_director_id",
        "tournament_tier",
        "tournament_website",
        "tournament_phone",
        "tournament_email",
        "total_players",
        "tournament_classification",
        "event_results_status",
        "pdga_latest_update",
        "pro_prize_money",
        "tournament_type",
        "players",
    ]